services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      default:
    # network_mode: host
    volumes:
      - media-volume:/docbot
      # - ./pdf_generator/output:/pdf_generator/output:z
    restart: always
    security_opt:
      - apparmor=unconfined
    # dns:
    #   - 8.8.8.8
    #   - 8.8.4.4

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450


volumes:
  media-volume:

